```yaml
name: Task1 CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'TASK1/**'
  pull_request:
    branches:
      - main
    paths:
      - 'TASK1/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r TASK1/requirements.txt
      - name: Run Unit Tests
        run: pytest
        working-directory: TASK1/

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: TASK1/
          file: TASK1/Dockerfile
          push: true
          tags: avinash00725/hello-inference-task1:latest
```
